settings:
  title: 'Vasconcellos Status Page'
  url: 'vasconcellos.workers.dev' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: vasconcellos-casa
    name: Homepage
    description: 'Família Vasconcellos - Homepage'
    url: 'https://vasconcellos.casa/'
    method: GET
    linkable: false
    expectStatus: 200

  - id: vasconcellos-vaultwarden
    name: Vaultwarden
    description: 'Password manager'
    url: 'https://vaultwarden.vasconcellos.casa/alive'
    method: GET
    linkable: false
    expectStatus: 200

  - id: vasconcellos-jellyfin
    name: Jellyfin
    description: 'The Free Software Media System'
    url: 'https://jellyfin.vasconcellos.casa/health'
    method: GET
    linkable: false
    expectStatus: 200

  - id: vasconcellos-libreddit
    name: Libreddit
    description: 'Alternative private front-end to Reddit'
    url: 'https://libreddit.vasconcellos.casa/settings'
    method: GET
    linkable: false
    expectStatus: 200

  - id: vasconcellos-nitter
    name: Nitter
    description: 'Alternative Twitter front-end '
    url: 'https://nitter.vasconcellos.casa/'
    method: GET
    linkable: false
    expectStatus: 200